# This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: page-replacement-policy
    - DOXYFILE: $TRAVIS_BUILD_DIR/docs//page-replacement-policy
    - GH_REPO_REF: github.com/jaskirat1208/page-replacement-policy.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - make

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: bin/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: main